### ISSUE TITLE
USER STORY: Additional Comments

### ISSUE THREAD

**Issue by CapriceHolford** [CapriceHolford/My-First-Agile-Project#6]
### User Story 3:
In order to **add additional comments** as a user, _I can_ **use the additional comments  box on the poll before submitting**

### Acceptance Criteria 
- This option should be provided as a textbox
- This shouldn't be a required feature
- This should appear just before the submit button, at the end of the poll questions
- There should be a maximum word limit of 200

## Tasks 
- [ ] Create the HTML and CSS for the textbox 
- [ ] Create the code to implement the max word limit
- [ ] Test the completed functionality
